name: 自动运行

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6,17 * * *' # 每天运行 6:00, 17:00 两次


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v2
      - name: 安装 python
        uses: actions/setup-python@v2
      - name: 安装依赖
        run: pip3 install requests
      - name: 运行
        env:
          STUDENTID: ${{secrets.STUDENTID}}
          PASSWORD: ${{secrets.PASSWORD}}
          DESCRIPTION: ${{secrets.DESCRIPTION}}
          PLACES: ${{secrets.PLACES}}
          DELTA: ${{secrets.DELTA}}
        run: python3 main.py